### ISSUE TITLE
Mlt6.24.0 in windows. There is an undefined reference problem in mingw64 compilation

### ISSUE THREAD

**Issue by kensnowZ** [mltframework/mlt#642]
d=c++11 -I..  -DVERSION=\"6.24.0\" -fvisibility=hidden   -c -o MltTractor.o MltTractor.cpp
g++ -Wall -DPIC   -O2 -pipe -fno-tree-dominator-opts -fno-tree-pre -ffast-math    -g -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -Wall -W -Wwrite-strings -Wcast-qual -Wpointer-arith -Wcast-align -Wredundant-decls -DPIC -DMLTPP_EXPORTS -std=c++11 -I..  -DVERSION=\"6.24.0\" -fvisibility=hidden   -c -o MltTransition.o MltTransition.cpp
g++ -Wl,-enable-auto-import -shared -Wl,--output-def,libmlt++.def -o libmlt++-3.dll MltAudio.o  MltAnimation.o  MltConsumer.o  MltDeque.o  MltEvent.o  MltFactory.o  MltField.o  MltFilter.o  MltFilteredConsumer.o  MltFilteredProducer.o  MltFrame.o  MltGeometry.o  MltMultitrack.o  MltParser.o  MltPlaylist.o  MltProducer.o  MltProfile.o  MltProperties.o  MltPushConsumer.o  MltRepository.o  MltService.o  MltTokeniser.o  MltTractor.o  MltTransition.o -L../framework -lmlt -Wl,--no-undefined -Wl,--as-needed
MltAudio.o:D:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\msys\home\37194\src\mlt-6.24.0\src\mlt++/MltAudio.cpp:36: undefined reference to `mlt_audio_close'
MltAudio.o: In function `Mlt::Audio::Audio()':
D:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\msys\home\37194\src\mlt-6.24.0\src\mlt++/MltAudio.cpp:26: undefined reference to `mlt_audio_new'
MltAudio.o: In function `Mlt::Audio::~Audio()':
D:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\msys\home\37194\src\mlt-6.24.0\src\mlt++/MltAudio.cpp:36: undefined reference to `mlt_audio_close'
MltAnimation.o: In function `Mlt::Animation::get_item(int, bool&, mlt_keyframe_type&)':
D:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\msys\home\37194\src\mlt-6.24.0\src\mlt++/MltAnimation.cpp:75: undefined reference to `mlt_animation_get_item'
MltAnimation.o: In function `Mlt::Animation::is_key(int)':
D:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\msys\home\37194\src\mlt-6.24.0\src\mlt++/MltAnimation.cpp:89: undefined reference to `mlt_animation_get_item'
MltAnimation.o: In function `Mlt::Animation::keyframe_type(int)':
D:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\msys\home\37194\src\mlt-6.24.0\src\mlt++/MltAnimation.cpp:97: undefined reference to `mlt_animation_get_item'
MltAnimation.o: In function `Mlt::Animation::next_key(int)':
D:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\msys\home\37194\src\mlt-6.24.0\src\mlt++/MltAnimation.cpp:108: undefined reference to `mlt_animation_next_key'
MltAnimation.o: In function `Mlt::Animation::previous_key(int)':
D:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\msys\home\37194\src\mlt-6.24.0\src\mlt++/MltAnimation.cpp:119: undefined reference to `mlt_animation_prev_key'
MltAnimation.o: In function `Mlt::Animation::key_get(int, int&, mlt_keyframe_type&)':
D:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\msys\home\37194\src\mlt-6.24.0\src\mlt++/MltAnimation.cpp:135: undefined reference to `mlt_animation_key_get'
MltAnimation.o: In function `Mlt::Animation::key_get_frame(int)':
D:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\msys\home\37194\src\mlt-6.24.0\src\mlt++/MltAnimation.cpp:149: undefined reference to `mlt_animation_key_get'
MltAnimation.o: In function `Mlt::Animation::key_get_type(int)':
D:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\msys\home\37194\src\mlt-6.24.0\src\mlt++/MltAnimation.cpp:160: undefined reference to `mlt_animation_key_get'
MltAnimation.o: In function `Mlt::Animation::length()':
D:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\msys\home\37194\src\mlt-6.24.0\src\mlt++/MltAnimation.cpp:68: undefined reference to `mlt_animation_get_length'
MltAnimation.o: In function `Mlt::Animation::key_count()':
D:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\msys\home\37194\src\mlt-6.24.0\src\mlt++/MltAnimation.cpp:128: undefined reference to `mlt_animation_key_count'
MltAnimation.o: In function `Mlt::Animation::key_set_type(int, mlt_keyframe_type)':
D:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\msys\home\37194\src\mlt-6.24.0\src\mlt++/MltAnimation.cpp:169: undefined reference to `mlt_animation_key_set_type'
MltAnimation.o: In function `Mlt::Animation::key_set_frame(int, int)':
D:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\msys\home\37194\src\mlt-6.24.0\src\mlt++/MltAnimation.cpp:174: undefined reference to `mlt_animation_key_set_frame'
MltAnimation.o: In function `Mlt::Animation::set_length(int)':
D:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\msys\home\37194\src\mlt-6.24.0\src\mlt++/MltAnimation.cpp:179: undefined reference to `mlt_animation_set_length'
MltAnimation.o: In function `Mlt::Animation::remove(int)':
D:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\msys\home\37194\src\mlt-6.24.0\src\mlt++/MltAnimation.cpp:184: undefined reference to `mlt_animation_remove'
MltAnimation.o: In function `Mlt::Animation::interpolate()':
D:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\msys\home\37194\src\mlt-6.24.0\src\mlt++/MltAnimation.cpp:189: undefined reference to `mlt_animation_interpolate'
MltAnimation.o: In function `Mlt::Animation::serialize_cut(int, int)':

ask for help thanks

**Comment by bmatherly** [comment]
This can happen if the linker finds an old version of libmlt before it finds the new version. Make sure that you have uninstalled any old versions of libmlt so that the linker will only find the new version in D:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\msys\home\37194\src\mlt-6.24.0\src\framework

**Comment by kensnowZ** [comment]
> 
I make sure there are no legacy libraries locally. But there are still such mistakes. Could you be more specific. Thank you very much.

**Comment by bmatherly** [comment]
All the symbols are defined in libmlt which is built from the code in the framework directory. I do not know why your linker is not finding them. Maybe you can use a tool like ldd to inspect the symbols in the libmlt library.

**Comment by kensnowZ** [comment]
> All the symbols are defined in libmlt which is built from the code in the framework directory. I do not know why your linker is not finding them. Maybe you can use a tool like ldd to inspect the symbols in the libmlt library.

Thank you. The problem is solved. But there is another problem. Appears when compiling melt. I feel that there is something wrong with the configuration of an environment.

make[1]: Entering directory `/home/37194/src/mlt-6.24.0/src/melt'
gcc -c -I/home/37194/include -Wall -DPIC   -O2 -pipe -fno-tree-dominator-opts -fno-tree-pre -ffast-math    -g -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -Wall -DPIC   -O2 -pipe -fno-tree-dominator-opts -fno-tree-pre -ffast-math    -g -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I..  -DVERSION=\"6.24.0\" -DHAVE_SDL2 -Dmain=SDL_main -ID:/mingw-w64/x86_64-8.1.0-win32-seh-rt_v6-rev0/mingw64/msys/home/37194/include/SDL2    -o melt.o melt.c
gcc -o melt melt.o  io.o -Wl,--no-undefined -Wl,--as-needed -L../framework -lmlt -lpthread -mwindows -LD:/mingw-w64/x86_64-8.1.0-win32-seh-rt_v6-rev0/mingw64/msys/home/37194/lib -lmingw32 -lSDL2main -lSDL2   -mconsole
melt.o: In function `on_fatal_error':
D:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\msys\home\37194\src\mlt-6.24.0\src\melt/melt.c:727: undefined reference to `mlt_properties_set_int'
melt.o: In function `on_jack_stopped':
D:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\msys\home\37194\src\mlt-6.24.0\src\melt/melt.c:240: undefined reference to `mlt_properties_get_data'
D:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\msys\home\37194\src\mlt-6.24.0\src\melt/melt.c:243: undefined reference to `mlt_producer_set_speed'
D:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\msys\home\37194\src\mlt-6.24.0\src\melt/melt.c:244: undefined reference to `mlt_consumer_purge'
D:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\msys\home\37194\src\mlt-6.24.0\src\melt/melt.c:245: undefined reference to `mlt_producer_seek'
melt.o: In function `on_jack_started':
D:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\msys\home\37194\src\mlt-6.24.0\src\melt/melt.c:220: undefined reference to `mlt_properties_get_data'
D:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\msys\home\37194\src\mlt-6.24.0\src\melt/melt.c:223: undefined reference to `mlt_producer_get_speed'
D:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\msys\home\37194\src\mlt-6.24.0\src\melt/melt.c:225: undefined reference to `mlt_properties_get_data'
D:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\msys\home\37194\src\mlt-6.24.0\src\melt/melt.c:230: undefined reference to `mlt_producer_set_speed'
D:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\msys\home\37194\src\mlt-6.24.0\src\melt/melt.c:231: undefined reference to `mlt_consumer_purge'
D:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\msys\home\37194\src\mlt-6.24.0\src\melt/melt.c:232: undefined reference to `mlt_producer_seek'

**Comment by bmatherly** [comment]
What was the solution?

It looks like melt has the same problem. All the undefined symbols are provided by libmlt from the framework directory.

I see the command includes `-L../framework -lmlt` which should instruct the linker to look in the framework directory to find the symbols that are missing. I do not know why they are still not found.

**Comment by kensnowZ** [comment]
> 解决方案是什么？
> 
> 看来融化有同样的问题。libmlt从框架目录提供所有未定义的符号。
> 
> 我看到命令包含在内`-L../framework -lmlt`，该命令应指示链接程序在框架目录中查找以查找缺少的符号。我不知道为什么仍然找不到它们。

I don't know what the problem is. I added the link path directly to the makefile file. It's strange. But it works

**Comment by kensnowZ** [comment]
> What was the solution?
> 
> It looks like melt has the same problem. All the undefined symbols are provided by libmlt from the framework directory.
> 
> I see the command includes `-L../framework -lmlt` which should instruct the linker to look in the framework directory to find the symbols that are missing. I do not know why they are still not found.

I don't know what the problem is. I added the link path directly to the makefile file. It's strange. But it works
